#!/usr/bin/env bash
# a Bash script that will display information about subdomains.

func() {
    rec=$(dig "$2.$1" | grep -A1 'ANSWER SECTION:' | awk '/.tech/{print $4}')
    ip=$(dig "$2.$1" | grep -A1 'ANSWER SECTION:' | awk '/.tech/{print $5}')
    echo "The subdomain $2 is a $rec record and points to $ip"
}

if [ "$#" == 1 ]
then
  func "$1" "www"
  func "$1" "lb-01"
  func "$1" "web-01"
  func "$1" "web-02"
elif [ "$#" == 2 ]
then
  func "$1" "$2"
fi
