#!/usr/bin/env bash
# installing nginx and configuring it's files.

apt-get update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
mkdir -p /var/www/html
chmod 755 /var/www/html
echo 'Hello World!' > /var/www/html/index.html
service nginx start
