#!/usr/bin/env bash
# installing nginx and configuring it's files.

apt-get update
apt-get -y install nginx
mkdir /etc/nginx/html
echo "Hello World!" > /etc/nginx/html/index.html

new_cmd='server {
    listen  80 default_server;
    listen [::]:80 default_server;
    root /etc/nginx/html;
    index index.html index.htm;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}'

echo "$new_cmd" > /etc/nginx/sites-available/default
service nginx restart
