#!/usr/bin/env bash
# installing nginx and configuring it's files.

apt-get update
apt-get -y install nginx
mkdir /etc/nginx/html
echo "Hello World!" > /etc/nginx/html/index.html
echo "Ceci n'est pas une page" > /etc/nginx/html/404.html

new_cmd='server {
    listen  80 default_server;
    listen [::]:80 default_server;
    root /etc/nginx/html;
    index index.html index.htm;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    error_page 404 /404.html;
    
    location /404 {
        root /etc/nginx/html;
        internal;
    }
    add_header X-Served-By $HOSTNAME;
}'

echo "$new_cmd" > /etc/nginx/sites-available/default
service nginx restart
