#!/usr/bin/env bash
# installing nginx and configuring it's files.

new_cmd='server {
    listen  80 default_server;
    listen [::]:80 default_server;
    root /etc/nginx/html;
    index index.html index.htm;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    error_page 404 /404.html;
    
    location /404 {
        root /etc/nginx/html;
        internal;
    }
    add_header X-Served-By $hostname;
}'

echo "$new_cmd" > /etc/nginx/sites-available/default
service nginx restart
