#!/usr/bin/env bash
# Fixing my nginx server to listen to my port 80
rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
