#!/usr/bin/env bash
# prints best school 10X using while loop bad lack for 4 and good luck for 8
c=1
while [ $c -le 10 ]
do
	if [ $c = 4 ]
	then
		echo bad luck
	elif [ $c = 8 ]
	then
		echo good luck
	else
		echo Best School
	fi
	((c++))
done
