#!/usr/bin/env bash
# prints best school 10X using while loop
c=1
while [ $c -le 20 ]
do
	case $c in
	4)
		echo bad luck from China
	;;
	9)
		echo bad luck from Japan
	;;
	17)
		echo bad luck from Italy
	;;
	*)
		echo $c
	;;
	esac
	((c++))
done
